on:
  workflow_run:
    workflows: ["Build cache on all supported plateforms"]
    types: 
      - completed
name: Build on all plateforms
env:
  GOPROXY: "https://proxy.golang.org"
jobs:
  build:
    strategy:
      matrix:
        go: [1.14.x, 1.15.x]
        goos: [linux, darwin]
        goarch: [amd64, arm]
        exclude:
          # windows/386 and darwin/386 seems useless
          - goarch: "arm"
            goos: darwin
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Install Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: build
      run: go build .
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}