on: [pull_request]
name: CI on Linux/amd64 latest stable Go Release
env:
  GOPROXY: "https://proxy.golang.org"
  GOVERSION: "1.15.x"
jobs:
  build-and-test:
    strategy:
      matrix:
        buildtag: [none, avx, sse]
    runs-on: "ubuntu-latest"
    steps:
    - name: Install Go 
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVERSION }}
    # Get values for cache paths to be used in later steps
    - id: go-cache-paths
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"
    - name: Checkout
      uses: actions/checkout@v2
    # Cache go build cache, used to speedup go test
    - name: Go Build Cache
      id: build-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build- 
    # Cache go mod cache, used to speedup builds
    - name: Go Mod Cache
      id: build-mod-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod- 
    - name: Install Dependencies
      if: steps.build-mod-cache.outputs.cache-hit != 'true'
      run: |
        GOARCH=arm GOOS=linux go get -t .
        GOARCH=amd64 GOOS=linux go get -t .
        GOARCH=amd64 GOOS=darwin go get -t .
    - name: Build without tags
      if: ${{ matrix.tags }} == 'none'
      run: |
        GOARCH=arm GOOS=linux go build . 
        GOARCH=amd64 GOOS=linux go build .
        GOARCH=amd64 GOOS=darwin go build .
    - name: Test without tags
      if: ${{ matrix.tags }} == 'none'
      run: |
        go test -v -race -timeout 20m
    - name: Build with tag
      if: ${{ matrix.tags }} != 'none'
      run: |
        build -tags=${{ matrix.tags }}
    - name: Test with tag
      if: ${{ matrix.tags }} != 'none'
      run: |
        go test -v -race -timeout 20m -tags=${{ matrix.tags }}
